### PR TITLE
Add CMake install command

### PR DESCRIPTION
**Pull request by flipback**
*Issue #309*

*Description of changes:*

I added cmake install commands to install libraries and public headers.

The file structure for installing:

```
.
├── include
│   └── aws_iot
│       ├── aws_iot_defender.h
│       ├── aws_iot_doc_parser.h
│       ├── aws_iot.h
│       ├── aws_iot_jobs.h
│       ├── aws_iot_shadow.h
│       ├── iot_error.h
│       ├── iot_init.h
│       ├── iot_linear_containers.h
│       ├── iot_logging.h
│       ├── iot_logging_setup.h
│       ├── iot_mqtt.h
│       ├── iot_mqtt_serialize.h
│       ├── iot_serializer.h
│       ├── iot_static_memory.h
│       ├── iot_taskpool.h
│       ├── platform
│       │   ├── iot_atomic.h
│       │   ├── iot_clock.h
│       │   ├── iot_metrics.h
│       │   ├── iot_network.h
│       │   ├── iot_network_mbedtls.h
│       │   ├── iot_network_metrics.h
│       │   └── iot_threads.h
│       └── types
│           ├── aws_iot_jobs_types.h
│           ├── aws_iot_shadow_types.h
│           ├── iot_mqtt_types.h
│           ├── iot_platform_types.h
│           ├── iot_platform_types_posix.h
│           └── iot_taskpool_types.h
└── lib
    ├── libawsiotcommon.so
    ├── libawsiotdefender.so
    ├── libawsiotjobs.so
    ├── libawsiotshadow.so
    ├── libiotbase.so
    ├── libiotmqtt.so
    └── libiotserializer.so

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by gordonwang0** [comment]
Hi @flipback,

Thank you for making this contribution!  As you can see from #309, this has been in our backlog for a while.

I noticed some issues that should be resolved before merging this.  We are happy to work with you for this.

1. Please use [GNUInstallDirs from cmake](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) instead of directory names like `lib` and `include`.  This module provides variables `${CMAKE_INSTALL_FULL_LIBDIR}` and `${CMAKE_INSTALL_FULL_INCLUDEDIR}` to represent `lib` and `include`, respectively.
1. Please see [RPATH handling](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling) to set the runtime path for the installed libraries.  (Otherwise, executables linked with these libraries will not work).
1. A config header `iot_config.h` should be generated and installed with these libraries.  At the very least, this config header will need to include `iot_platform_types_posix.h`
1. The CMakeLists.txt files placed with the libraries ideally contain platform-independent build commands.  We do not want to introduce platform-specific install commands there.  I propose creating CMake functions of the install commands and placing them in a new file such as `ports/posix/install_posix.cmake`.  Then do the following to pull in the platform-specific install commands in each CMakeLists.txt:
```
# Set some variables representing the header and target to be installed,
# then call:
include( ${PROJECT_SOURCE_DIR}/ports/install_${IOT_PLATFORM_NAME}/${IOT_PLATFORM_NAME}.cmake OPTIONAL )
```

I realize the above is a non-trivial amount of work; please don't feel pressured to do it all unless your schedule permits.  This pull request is already very helpful for us in implementing the install commands, and we will use it as a starting point.  Thank you!

**Comment by flipback** [comment]
Hi @gordonwang0 , 
Thank you for your answer and offer to work on the PR together. I tried to fulfill your recommendations. The new version is working on my local machine well, but I've broken your CI. I'm not sure but your CI environment seems to work without third-party dependencies.  I need your advice how to work around this properly.

**Comment by sarenameas** [comment]
Hello @flipback,
We have discussed this issue internally and realize and there some decisions that need to be addressed before moving forward with this feature and continuing on the current path. We really appreciate all of the work you have done to push this forward and it is valuable for us to use when bringing this feature to completion. We will prioritize this issue internally, thanks again!

**Comment by flipback** [comment]
Hi @sarenameas, no problem at all. Thank you for the infromation.

**Comment by sarenameas** [comment]
@flipback I am going to close this PR for now. Thanks again for your hard work.

**Pull request closed without merging**
