### PR TITLE
Remove demo-specific identifiers from diagrams

### PR DESCRIPTION
**Pull request by sukhmanm**
*Description of changes:* Removed all references to demo-specific macros, function names, etc. in the diagrams to remove clutter and provide a more high-level description of the applications, while highlighting the MQTT API. Also made minor design changes.

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

### CODE REVIEW

**Comment by sarenameas** [comment]
Can you rename the files to lowercase .png or update the references to the them using @image in the documentation to use the upper case .PNG so that we do not get warnings on a real unix platform?

**Comment by aggarw13** [comment]
image

The above text can be re-phrased as "Check if subscription attempt was successful from SUBACK response"

**Comment by aggarw13** [comment]
image

This text can be re-worded as "Remove PUBLISH message from demo cache as PUBLISH succeeded "

**Comment by aggarw13** [comment]
It would be good to have the topics for subscription requests, outgoing PUBLISH and incoming PUBLISH messages mentioned in all the demo diagrams (like it has been done for the subscription manager)

**Comment by aggarw13** [comment]
image

The MQTT library bar can include both the outgoing PUBLISH and incoming PUBLISH arrows as the `ProcessLoop` function takes care of both operations (of completing the outgoing PUBLISH and processing the incoming PUBLISH).

Also, the incoming PUBLISH text can mention "PUBLISH to topic /demo/temperature/high"

**Comment by aggarw13** [comment]
image

Similarly, the incoming PUBLISH text can explicitly mention the topic as "PUBLISH to topic /example/topic" so that the workflow is clear to the customer.

**Comment by aggarw13** [comment]
image

The text should be "Establish TLS Session with server-only authentication"

**Comment by aggarw13** [comment]
image

Similarly, this can say "Establish TLS session with client credentials & server root CA certificate (OpenSSL)"

**Comment by aggarw13** [comment]
image

Suggesting changing `SOCKETS` -> `POSIX SOCKETS`

**Comment by aggarw13** [comment]
In the serializer demo, the arrow of server response of ack packets (CONNACK, SUBACK, PUBACK, UNSUBACK) and incoming PUBLISH should go _directly_ to the Demo instead of the MQTT library as the send and receive in this demo are done by the demo application.

image

**Comment by aggarw13** [comment]
image

This diagram mentions about PINGREQ being sent out but no PINGRESP being received from the server and processed by the demo.

**Review by aggarw13 — DISMISSED** [review]

**Review by aggarg — APPROVED** [review]

**Review by aggarw13 — DISMISSED** [review]

**Review by aggarw13 — APPROVED** [review]

**Review by aggarg — APPROVED** [review]

**Pull request merged**
